import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const roots = ['src/content/projects', 'src/pages']
const hits = []

function walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    if (e.isDirectory()) { walk(p); continue }
    if (!/\.(md|astro)$/.test(e.name)) continue
    readFileSync(p, 'utf8').split('\n').forEach((line, i) => {
      const m = line.match(/TODO_[A-Z_]+|PASTE_VERBATIM_FROM_ARCHIVE/)
      if (m) hits.push(`- [ ] \`${p}:${i + 1}\` — ${m[0]}`)
    })
  }
}
roots.forEach(walk)

const body = `# Content TODO\n\nGenerated by \`npm run todos\`. ${hits.length} item(s) outstanding.\n\n${hits.join('\n')}\n\n## Also needed\n- [ ] \`public/resume.pdf\` — résumé file\n- [ ] Real images (Phase 4) to replace gray placeholders\n`
writeFileSync('CONTENT-TODO.md', body)
console.log(`${hits.length} content TODO(s) — see CONTENT-TODO.md`)
