// Scans the source for placeholder markers and writes CONTENT-TODO.md — a checklist of
// what Bryan still has to supply, with exact file paths and line numbers.
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const roots = ['src/content/projects', 'src/pages']
const hits = []

function walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    if (e.isDirectory()) { walk(p); continue }
    if (!/\.(md|astro)$/.test(e.name)) continue
    readFileSync(p, 'utf8').split('\n').forEach((line, i) => {
      const m = line.match(/TODO_[A-Z_]+|PASTE_VERBATIM_FROM_ARCHIVE/)
      if (m) hits.push('- [ ] `' + p + ':' + (i + 1) + '` — ' + m[0])
    })
  }
}
roots.forEach(walk)

// Projects still showing a grey placeholder rather than real photographs.
const projDir = 'src/content/projects'
const slugs = readdirSync(projDir).filter(f => f.endsWith('.md')).map(f => f.replace(/\.md$/, ''))
const withImages = slugs.filter(s => existsSync(join('src/assets/projects', s)))
const missing = slugs.filter(s => !withImages.includes(s))

// Design questions are optional by design — a project renders one only when the field is
// set. An unset question is not a blocker, so it is reported separately from the markers.
const noQuestion = slugs.filter(s =>
  /^designQuestion: null$/m.test(readFileSync(join(projDir, s + '.md'), 'utf8')))

const lines = [
  '# Content TODO',
  '',
  'Generated by `npm run todos`. ' + hits.length + ' blocking marker(s).',
  '',
  hits.length ? hits.join('\n') : '_No placeholder markers left in source._',
  '',
  '## Optional — not blocking',
  '',
  '- Design questions: ' + noQuestion.length + ' of ' + slugs.length + ' projects have none.',
  '  A project shows one only when `designQuestion` is set; leave it `null` and nothing',
  '  renders. Draft in `DESIGN-QUESTIONS.md`, then set the value.',
  '',
  '## Still needed',
  '',
  '- [ ] Real images — ' + withImages.length + ' of ' + slugs.length + ' projects have photographs.',
  missing.length ? '      Missing: ' + missing.join(', ') : '',
  '',
].filter(l => l !== '')

writeFileSync('CONTENT-TODO.md', lines.join('\n') + '\n')
console.log(hits.length + ' blocking marker(s); ' + noQuestion.length + ' projects without a design question; images on ' + withImages.length + '/' + slugs.length + ' — see CONTENT-TODO.md')
